#!/bin/bash
# makectan
# The shell script for preparing a CTAN LaTeX package installer and its requirement
# Copyright 2018 Ratthaprom Promkam
# Usage   makectan <type> <name>
#
#         type      Type of CTAN package installer which can be either
#                     package or class.
#         name      Name of a CTAN package/class in the directories
#                     Classes or Packages.

version="2021.03.01"

ctantype=$1
pkgname=$2
author="Ratthaprom_Promkam"

echo "This is makectan (version $version)."
echo "Make $ctantype: $pkgname"
if [ $ctantype = "package" ]; then
  cd package/$pkgname || exit
  makedtx -author $author -src "${pkgname}\.sty=>${pkgname}.sty" -doc ${pkgname}.tex $pkgname
fi
if [ $ctantype = "class" ]; then
  cd class/$pkgname || exit
  makedtx -author $author -src "${pkgname}\.cls=>${pkgname}.cls" -doc ${pkgname}.tex $pkgname
fi

echo "${pkgname}.dtx and ${pkgname}.ins created successfully."
zip ${pkgname}.zip ${pkgname}.dtx ${pkgname}.ins README.md ${pkgname}.pdf
rm ${pkgname}.dtx ${pkgname}.ins
echo "./${ctantype}/${pkgname}/${pkgname}.zip ready to upload to CTAN."
