#!/bin/sh
texengin=$1
name=$2
$texengin -interaction=nonstopmode -output-directory=./.tmp $name
$texengin -interaction=nonstopmode -output-directory=./.tmp $name
mkdir -p ./OutputDir/$name
mv ./.tmp/*.pdf ./OutputDir/$name
