#!/bin/bash
texname=$1
texengine=$(grep -E '%\s*!TEX\s*(program|engine)\s*=\s*' ${texname}.tex | sed -E 's:.+= *::')
$texengine -synctex=1 -interaction=nonstopmode -file-line-error -output-directory=.tmp $texname
open .tmp/${texname}.pdf
